---
- name: Create BookHaven Docker network
  community.docker.docker_network:
    name: "{{ mongo_network }}"
    state: present

- name: Create MongoDB volume
  community.docker.docker_volume:
    name: "{{ mongo_volume }}"
    state: present

- name: Run MongoDB container
  community.docker.docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "{{ mongo_volume }}:/data/db"
    networks:
      - name: "{{ mongo_network }}"
  tags:
    - database