---
- name: Pull image from repository
  community.docker.docker_image:
    name: "{{ backend_image }}"
    source: pull

- name: Create Node.js Backend Container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    networks:
      - name: "{{ backend_network }}"
    ports:
      - "{{ backend_host_port }}:{{ backend_container_port }}"
    env:
      MONGODB_URI: "{{ backend_mongodb_uri }}"
      PORT: "{{ backend_port }}"
    command: "npm start"
    state: started
    restart_policy: unless-stopped
