apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: bookhaven
    component: database
spec:
  clusterIP: None
  selector:
    app: bookhaven
    component: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb